### ISSUE TITLE
No 'current-planetary-positions/sweph/isabelse' File Found in Plugin

### ISSUE THREAD

**Issue by Katyah** [isabelc/current-planetary-positions#8]
Hi, thanks for creating this great plugin. For 9-10 days I've had MAJOR difficulty connecting to the correct Swiss Ephemeris info through your plugin. I've read your advise on your troubleshooting page below & the file you listed doesn't exist in the plugin. Is this old info?: 

"All Positions Are Stuck on Aries
The plugin includes a file that must have permission to execute (CHMOD 755) in order to get the planetary positions from the Swiss Ephemeris. The file is:
current-planetary-positions/sweph/isabelse "

All my permissions are correct. My web host doesn't block exec(). This plugin worked perfectly for many months before. Please advise.

**Comment by isabelc** [comment]
Yes, in version 1.3.1 the file that needs 755 permissions has changed to:
`current-planetary-positions/sweph/swetest`
